trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .changeset/*.md

pool:
  vmImage: 'ubuntu-latest'
variables:
    - group: common-vg
jobs:
- job: Release_new_version
  steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '18.x'

  - checkout: self
    persistCredentials: true

  - script: |
      # Rename package.json
      mv package.json package_old.json

      # Install Changeset CLI
      npm install @changesets/cli --no-save --no-package-lock

      # Rename package_old.json to package.json
      mv package_old.json package.json

      # Bump version and create changelog with Changeset
      npx @changesets/cli --version

      # Log in to npm
      echo "//registry.npmjs.org/:_authToken=$(npm-token)" > .npmrc

      # Publish the package using Changesets
      npx @changesets/cli publish

      VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | awk '{$1=$1};1' | sed 's/[",]//g')
      LASTCOMMIT=$(git rev-parse --short HEAD)
      # Commit changes
      git config --global user.email "no-reply@carasent.com"
      git config --global user.name "npx changeset"
      git remote set-url origin 'https://dev.azure.com/avanssoma/Arbeidoginkludering/_git/asma-core-ui'
      git tag -a "v${VERSION}" "${LASTCOMMIT}" -m "Version - ${VERSION}"
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push --tag
    displayName: 'Bump version and publish package'
