module.exports = {
    // 'text-component': 'var(--colors-gray-9000)',
    // 'active-component': 'var(--colors-gama-700)',
    //
    // 'alpha-100': 'var(--colors-slate-100)',
    // 'alpha-500': 'var(--colors-slate-500)',
    // 'alpha-600': 'var(--colors-slate-600)',
    // 'alpha-700': 'var(--colors-slate-700)',
    //
    'beta-100': 'var(--colors-red-100)',
    'beta-500': 'var(--colors-red-500)',
    'beta-600': 'var(--colors-red-600)',
    'beta-700': 'var(--colors-red-700)',
    //
    'gama-100': 'var(--colors-jade-100)',
    'gama-200': 'var(--colors-jade-200)',
    'gama-300': 'var(--colors-jade-300)',
    'gama-400': 'var(--colors-jade-400)',
    'gama-500': 'var(--colors-jade-500)',
    'gama-600': 'var(--colors-jade-600)',
    'gama-700': 'var(--colors-jade-700)',
    'gama-800': 'var(--colors-jade-800)',
    //
    'delta-100': 'var(--colors-gray-100)',
    'delta-200': 'var(--colors-gray-200)',
    'delta-300': 'var(--colors-gray-300)',
    'delta-400': 'var(--colors-gray-400)',
    'delta-500': 'var(--colors-gray-500)',
    'delta-600': 'var(--colors-gray-600)',
    'delta-700': 'var(--colors-gray-600)',
    'delta-800': 'var(--colors-gray-600)',
    'delta-900': 'var(--colors-gray-900)',
    // should be removed in the future
    'delta-9000': 'var(--colors-gray-9000)',
    'delta-10000': 'var(--colors-gray-10000)',

    'theta-100': 'var(--colors-jade-100)',
    'theta-200': 'var(--colors-jade-200)',
    'theta-300': 'var(--colors-jade-300)',
    'theta-400': 'var(--colors-jade-400)',
    'theta-500': 'var(--colors-jade-500)',
    'theta-600': 'var(--colors-jade-600)',
    'theta-700': 'var(--colors-jade-700)',
    'theta-800': 'var(--colors-jade-800)',

    'sigma-700': 'var(--colors-jade-500)',
    // 'sigma-700': 'var(--colors-gray-700)',
    // 'zeta-700': 'var(--colors-gray-700)',
    // button
    // 'btn-bg-hover': 'var(--colors-gama-600)',
    // 'btn-bg-standart': 'var(--colors-gama-500)',
    // 'btn-bg-active': 'var(--colors-gama-600)',
    // 'btn-bg-disabled': 'var(--colors-gray-200)',
    // 'btn-bg-danger': 'var(--colors-red-700)',
    // 'btn-bg-danger-active': 'var(--colors-red-500)',
    // mini action button (delete,edit)
    // 'colors-btn-bg-mini-action': 'var(--colors-gray-100)',
    // 'colors-btn-bg-mini-action-hover': 'var(--colors-gama-700)',
    // link
    'link-text-hover': '#ffffff',
    'link-text-standart': '#ffffff',
    'link-text-active': '#ffffff',
    'link-text-disabled': 'var(--colors-gray-200)',
    // badge
    'badge-bg': 'var(--colors-lime-500)',
    'badge-text': 'var(--colors-jade-600)',

    // custom
    // 'app-directory-button-select-recipient-bg': 'var(--colors-slate-500)',

    //
    // 'btn-task-status-bg': 'var(--colors-green-100)',

    // 'chat-ticket-message-bg': 'var(--colors-alpha-500)',
    //
    // 'colors-topbar-text': '#ffffff',

    // New buttons
    // Primary button
    'button-primary-text-color': '#ffffff',
    'button-primary-bg-color': 'var(--colors-gama-600)',
    'button-primary-border-color': 'var(--colors-gama-600)',
    'button-primary-focused-text-color': '#ffffff',
    'button-primary-focused-bg-color': 'var(--colors-gama-600)',
    'button-primary-focused-border-color': 'var(--colors-yellow-400)',
    'button-primary-active-text-color': '#ffffff',
    'button-primary-active-bg-color': 'var(--colors-gama-800)',
    'button-primary-active-border-color': 'var(--colors-gama-800)',
    'button-primary-hover-text-color': '#ffffff',
    'button-primary-hover-bg-color': 'var(--colors-gama-700)',
    'button-primary-hover-border-color': 'var(--colors-gama-700)',
    'button-primary-disabled-text-color': '#ffffff',
    'button-primary-disabled-bg-color': 'var(--colors-delta-400)',
    'button-primary-disabled-border-color': 'var(--colors-delta-400)',
    // Secondary button
    'button-secondary-text-color': 'var(--colors-gama-600)',
    'button-secondary-bg-color': 'transparent',
    'button-secondary-border-color': 'var(--colors-gama-600)',
    'button-secondary-focused-text-color': 'var(--colors-gama-600)',
    'button-secondary-focused-bg-color': 'transparent',
    'button-secondary-focused-border-color': 'var(--colors-yellow-400)',
    'button-secondary-active-text-color': '#ffffff',
    'button-secondary-active-bg-color': 'var(--colors-gama-800)',
    'button-secondary-active-border-color': 'var(--colors-gama-800)',
    'button-secondary-hover-text-color': '#ffffff',
    'button-secondary-hover-bg-color': 'var(--colors-gama-700)',
    'button-secondary-hover-border-color': 'var(--colors-gama-700)',
    'button-secondary-disabled-text-color': '#ffffff',
    'button-secondary-disabled-bg-color': 'var(--colors-delta-400)',
    'button-secondary-disabled-border-color': 'var(--colors-delta-400)',
    // Flat button
    'button-flat-text-color': 'var(--colors-gama-600)',
    'button-flat-bg-color': 'transparent',
    'button-flat-border-color': 'var(--colors-gama-600)',
    'button-flat-focused-text-color': 'var(--colors-gama-600)',
    'button-flat-focused-bg-color': 'transparent',
    'button-flat-focused-border-color': 'var(--colors-yellow-400)',
    'button-flat-active-text-color': '#ffffff',
    'button-flat-active-bg-color': 'var(--colors-gama-800)',
    'button-flat-active-border-color': 'var(--colors-gama-800)',
    'button-flat-hover-text-color': '#ffffff',
    'button-flat-hover-bg-color': 'var(--colors-gama-700)',
    'button-flat-hover-border-color': 'var(--colors-gama-700)',
    'button-flat-disabled-text-color': '#ffffff',
    'button-flat-disabled-bg-color': 'var(--colors-delta-400)',
    'button-flat-disabled-border-color': 'var(--colors-delta-400)',
    // Danger button
    'button-danger-text-color': '#ffffff',
    'button-danger-bg-color': 'var(--colors-beta-500)',
    'button-danger-border-color': 'var(--colors-beta-500)',
    'button-danger-focused-text-color': '#ffffff',
    'button-danger-focused-bg-color': 'var(--colors-beta-600)',
    'button-danger-focused-border-color': 'var(--colors-beta-600)',
    'button-danger-active-text-color': '#ffffff',
    'button-danger-active-bg-color': 'var(--colors-beta-700)',
    'button-danger-active-border-color': 'var(--colors-beta-700)',
    'button-danger-hover-text-color': '#ffffff',
    'button-danger-hover-bg-color': 'var(--colors-beta-600)',
    'button-danger-hover-border-color': 'var(--colors-beta-600)',
    'button-danger-disabled-text-color': '#ffffff',
    'button-danger-disabled-bg-color': 'var(--colors-beta-100)',
    'button-danger-disabled-border-color': 'var(--colors-beta-100)',

    'menu-text-active': 'var(--colors-jade-700)',
}
